source 'https://rubygems.org'

gem 'jekyll', '~> 4.2'

group :jekyll_plugins do
  gem 'jekyll-timeago', '~> 0.13.1'
  
  gem "jekyll-feed", "~> 0.12"
  # Jekyll SEO plugin
  gem "jekyll-seo-tag", "~> 2.1"
  # Jekyll Spaceship plugin
  gem "jekyll-spaceship"
  # Jekyll Sitemap plugin
  gem "jekyll-sitemap"
  # Jekyll Mermaid plugin
  gem "jekyll-mermaid"
  # Jekyll Remote Theme plugin
  gem "jekyll-remote-theme"
  
  gem "kramdown-parser-gfm"
end
